### ISSUE TITLE
Cannot read properties of undefined (reading 'meta')

### ISSUE THREAD

**Issue by luk-ada** [SAP/alm-plug-in-for-grafana#91] opened 2023-04-24 09:28 UTC
Hello

I have an error after plugin configuration. During the configuration everything looks fine. "Data Providers Settings" are visible and  I have green box "Data source is working". Then when I try to open Explorer I have below error message:.
Can you please advise?

```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'meta')

    at t (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:568276)
    at Ur (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:638387)
    at c (https://MY_GRAFANA_URL/public/build/8339.15467d3678c125574e97.js:71:1128)
    at ei (https://MY_GRAFANA_URL/public/build/explore.cd9df6b98b317bc08878.js:307:1252)
    at div
    at o (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:2181:861)
    at div
    at div
    at div
    at t (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:711588)
    at p (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:424:3279)
    at io (https://MY_GRAFANA_URL/public/build/explore.cd9df6b98b317bc08878.js:491:3571)
    at g (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1042468)
    at WithTheme(Connect(io))
    at div
    at co (https://MY_GRAFANA_URL/public/build/explore.cd9df6b98b317bc08878.js:514:3053)
    at g (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1042468)
    at WithTheme(Connect(co))
    at c (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:1207:301)
    at u (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:1207:855)
    at div
    at div
    at yo (https://MY_GRAFANA_URL/public/build/explore.cd9df6b98b317bc08878.js:530:350)
    at Suspense
    at c (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:1207:301)
    at ts (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:5576:348)
    at t (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1060861)
    at t (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1062882)
    at main
    at Rt (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:5537:6824)
    at t (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1057479)
    at div
    at o (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:2005:4594)
    at t.KBarProvider (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:271053)
    at l (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:6297:20329)
    at c (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:1207:301)
    at u (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:1207:855)
    at l (https://MY_GRAFANA_URL/public/build/4743.fc5befcd39e4d04d2f72.js:2:1040513)
    at As (https://MY_GRAFANA_URL/public/build/7180.b4c11f4be0293b7712ff.js:5589:167)
```

PS. I replaced real URL with MY_GRAFANA_URL

**Comment by vienlam** [comment] 2023-04-25 07:36
Hi @luk-ada ,

Investigating issue. Please use Dashboard instead of Explore function for now.

**Comment by luk-ada** [comment] 2023-04-25 11:24
Hi @vienlam 
It's not working in dashboard/panel view as well. Query is empty (can not put anything there):
![image](https://user-images.githubusercontent.com/45640151/234261460-70f0ae3c-8013-47e1-8e51-5981d3e7c54e.png)

I did not sign the plugin, I'm using whitelist variable. Could it be related?

**Comment by andreacampo** [comment] 2023-06-19 13:55
FYI, the issue starts from [Grafana 8.3.0](https://github.com/grafana/grafana/releases/tag/v8.3.0). There is a bugfix related to "Explore" but I am not sure this is the root cause.

**Comment by vienlam** [comment] 2023-08-07 12:20
This should be fixed in next release.

**Comment by andreacampo** [comment] 2023-11-02 10:18
Closed by https://github.com/SAP/alm-plug-in-for-grafana/commit/5f17a9adfc20c24ccdd076bc65e0e0e47223ecc3

**Closed by andreacampo** 2023-11-02 10:18 UTC
Labels: bug
